### ISSUE TITLE
g.build fails

### ISSUE THREAD

**Issue by christoph88** [edjames/pivot_table#11]
HI

When I do `g.build` (in my controller) like your readme mentions I get following error `comparison of String with nil failed`. Do you have any idea what could be the problem? I am literally messing with this for hours.

>  def no_category
>    @transactions = Transaction.all.limit(10)
>    g = grid(@transactions, { :row_name => :naam_tegenpartij, :column_name => :landcode })
>    g.build
>  end

My module code looks like this:

>module PivotTableBla
>  def grid(data, options = {})
>    grid = PivotTable::Grid.new do |g|
>      g.source_data = data
>      g.column_name = options[:column_name]
>      g.row_name = options[:row_name]
>    end
>  end
>end

**Comment by edjames** [comment]
Hi. Could you please post the full error trace for me?

**Comment by christoph88** [comment]
Hi, I made a backtrace using byebug. Is this what you need? I am quite new to this. 

Thanks in advance for looking into this.

> backtrace
> --> #0  LandingController.no_category at /home/christoph/Documenten/expenses/app/controllers/landing_controller.rb:11
>     #1  ActionController::ImplicitRender.send_action(method#String, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/implicit_render.rb:4
>     #2  AbstractController::Base.process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:198
>     #3  ActionController::Rendering.process_action(action, *args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:10
>     #4  block in AbstractController::Callbacks.block in process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:20
>     ͱ-- #5  Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117
>     #6  ActiveSupport::Callbacks::Filters::End.call(env#ActiveSupport::Callbacks::Filters::Environment) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117
>     #7  block in #<Class:ActiveSupport::Callbacks::Filters::After>.block in halting(next_callback#ActiveSupport::Callbacks::Filters::End, user_callback#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234
>     ͱ-- #8  Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234
>     #9  block in #<Class:ActiveSupport::Callbacks::Filters::After>.block in halting(next_callback#Proc, user_callback#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234
>     ͱ-- #10 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     #11 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(next_callback#Proc, user_callback#Proc, halted_lambda#Proc, filter#Symbol) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     ͱ-- #12 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     #13 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(next_callback#Proc, user_callback#Proc, halted_lambda#Proc, filter#Symbol) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     ͱ-- #14 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     #15 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(next_callback#Proc, user_callback#Proc, halted_lambda#Proc, filter#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     ͱ-- #16 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     #17 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(next_callback#Proc, user_callback#Proc, halted_lambda#Proc, filter#Symbol) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169
>     ͱ-- #18 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92
>     #19 ActiveSupport::Callbacks._run_callbacks(callbacks#ActiveSupport::Callbacks::CallbackChain, &block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92
>     #20 ActionController::Base._run_process_action_callbacks(&block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734
>     #21 ActiveSupport::Callbacks.run_callbacks(kind#Symbol, &block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81
>     #22 AbstractController::Callbacks.process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19
>     #23 ActionController::Rescue.process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29
>     #24 block in ActionController::Instrumentation.block in process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31
>     #25 block in #<Class:ActiveSupport::Notifications>.block in instrument(name#String, payload#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164
>     #26 ActiveSupport::Notifications::Instrumenter.instrument(name#String, payload#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20
>     #27 #<Class:ActiveSupport::Notifications>.instrument(name#String, payload#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164
>     #28 ActionController::Instrumentation.process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30
>     #29 ActionController::ParamsWrapper.process_action(action#NilClass, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250
>     #30 ActiveRecord::Railties::ControllerRuntime.process_action(action#String, *args#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18
>     #31 AbstractController::Base.process(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137
>     #32 ActionView::Rendering.process(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:30
>     #33 ActionController::Metal.dispatch(action#NilClass, request#ActionDispatch::Request) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195
>     #34 ActionController::RackDelegation.dispatch(action#String, request#ActionDispatch::Request) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13
>     #35 block in #<Class:ActionController::Metal>.block in action(name#String, klass#Class) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236
>     ͱ-- #36 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73
>     #37 ActionDispatch::Routing::RouteSet::Dispatcher.dispatch(controller#Class, action#String, env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73
>     #38 ActionDispatch::Routing::RouteSet::Dispatcher.serve(req#ActionDispatch::Request) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42
>     #39 block in ActionDispatch::Journey::Router.block in serve(req#ActionDispatch::Request) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43
>     ͱ-- #40 Array.each at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30
>     #41 ActionDispatch::Journey::Router.serve(req#ActionDispatch::Request) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30
>     #42 ActionDispatch::Routing::RouteSet.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802
>     #43 Rack::ETag.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24
>     #44 Rack::ConditionalGet.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25
>     #45 Rack::Head.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13
>     #46 ActionDispatch::ParamsParser.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27
>     #47 ActionDispatch::Flash.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260
>     #48 Rack::Session::Abstract::ID.context(env#Hash, app#ActionDispatch::Flash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225
>     #49 Rack::Session::Abstract::ID.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220
>     #50 ActionDispatch::Cookies.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560
>     #51 ActiveRecord::QueryCache.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36
>     #52 ActiveRecord::ConnectionAdapters::ConnectionManagement.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647
>     #53 ActiveRecord::Migration::CheckPending.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:378
>     #54 block in ActionDispatch::Callbacks.block in call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29
>     ͱ-- #55 Proc.call(*args) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88
>     #56 ActiveSupport::Callbacks._run_callbacks(callbacks#ActiveSupport::Callbacks::CallbackChain, &block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88
>     #57 ActionDispatch::Callbacks._run_call_callbacks(&block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734
>     #58 ActiveSupport::Callbacks.run_callbacks(kind#Symbol, &block#Proc) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81
>     #59 ActionDispatch::Callbacks.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27
>     #60 ActionDispatch::Reloader.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:73
>     #61 ActionDispatch::RemoteIp.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78
>     #62 BetterErrors::Middleware.protected_app_call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84
>     #63 BetterErrors::Middleware.better_errors_call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79
>     #64 BetterErrors::Middleware.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57
>     #65 ActionDispatch::DebugExceptions.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17
>     #66 WebConsole::Middleware.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/middleware.rb:39
>     #67 ActionDispatch::ShowExceptions.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30
>     #68 Rails::Rack::Logger.call_app(request#ActionDispatch::Request, env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38
>     #69 block in Rails::Rack::Logger.block in call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20
>     #70 block in ActiveSupport::TaggedLogging.block in tagged(*tags#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68
>     #71 ActiveSupport::TaggedLogging::Formatter.tagged(*tags#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26
>     #72 ActiveSupport::TaggedLogging.tagged(*tags#Array) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68
>     #73 Rails::Rack::Logger.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20
>     #74 ActionDispatch::RequestId.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21
>     #75 Rack::MethodOverride.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22
>     #76 Rack::Runtime.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18
>     #77 ActiveSupport::Cache::Strategy::LocalCache::Middleware.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28
>     #78 Rack::Lock.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17
>     #79 ActionDispatch::Static.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113
>     #80 Rack::Sendfile.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113
>     #81 Rails::Engine.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518
>     #82 Rails::Application.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164
>     #83 Rack::Lock.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17
>     #84 Rack::ContentLength.call(env#Hash) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15
>     #85 Rack::Handler::WEBrick.service(req#WEBrick::HTTPRequest, res#WEBrick::HTTPResponse) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88
>     #86 WEBrick::HTTPServer.service(req#WEBrick::HTTPRequest, res#WEBrick::HTTPResponse) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138
>     #87 WEBrick::HTTPServer.run(sock#TCPSocket) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94
>     #88 block in WEBrick::GenericServer.block in start_thread(sock#TCPSocket, &block#NilClass) at /home/christoph/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294
> 
>

**Comment by christoph88** [comment]
I am trying it with different fields and It looks like I have some nil values which are causing this problem. I did not understand what you meant with `This gem expects an aggregated dataset.` but it looks like that has something to do with it. For me this is fixed.

**Comment by edjames** [comment]
Ok great, glad to hear it's sorted now.
